/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zj_zfenlly_camera_CameraJni */

#ifndef _Included_zj_zfenlly_camera_CameraJni
#define _Included_zj_zfenlly_camera_CameraJni

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zj_zfenlly_camera_CameraJni
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zj_zfenlly_camera_CameraJni_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif
