package com.zfenlly.wb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zfenlly.wb.WB;

import com.zfenlly.wb.WBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wBDaoConfig;

    private final WBDao wBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wBDaoConfig = daoConfigMap.get(WBDao.class).clone();
        wBDaoConfig.initIdentityScope(type);

        wBDao = new WBDao(wBDaoConfig, this);

        registerDao(WB.class, wBDao);
    }
    
    public void clear() {
        wBDaoConfig.getIdentityScope().clear();
    }

    public WBDao getWBDao() {
        return wBDao;
    }

}
