package com.zfenlly.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mSCDaoConfig;
    private final DaoConfig wBDaoConfig;

    private final MSCDao mSCDao;
    private final WBDao wBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mSCDaoConfig = daoConfigMap.get(MSCDao.class).clone();
        mSCDaoConfig.initIdentityScope(type);

        wBDaoConfig = daoConfigMap.get(WBDao.class).clone();
        wBDaoConfig.initIdentityScope(type);

        mSCDao = new MSCDao(mSCDaoConfig, this);
        wBDao = new WBDao(wBDaoConfig, this);

        registerDao(MSC.class, mSCDao);
        registerDao(WB.class, wBDao);
    }

    public void clear() {
        mSCDaoConfig.getIdentityScope().clear();
        wBDaoConfig.getIdentityScope().clear();
    }

    public MSCDao getMSCDao() {
        return mSCDao;
    }

    public WBDao getWBDao() {
        return wBDao;
    }

}
